### ISSUE TITLE
Shared Calendars - take a look

### ISSUE THREAD

**Issue by ibo549** [ibo549/calREST#10]
This task consists of various sub-tasks which should be broken into individual issues;
- Create an entity to represent shared calendar schema. (id, CalendarId, SharedUserId, permissions)
- A repository to access necessary methods.
- A shared calendar service to actually share the calendar with other users via e-mail/facebook message.

**Comment by bszymik** [comment]
when user will be deleted (marked as inactive) - then collaboration should also be removed or deactivated?

**Comment by ibo549** [comment]
I think it should be deactivated. You can add an IsActive flag in my opinion.
