### ISSUE TITLE
Duplicate patients when posted through appointments

### ISSUE THREAD

**Issue by ibo549** [ibo549/calREST#28]
When an existing patient is being posted as part of an appointment - server side re-creates the patient instead of using the existing one.

**Comment by bszymik** [comment]
This is happening because received appointment object contains patient data, but appointment.PatientID is null
moreover appointment.Patient.OwnerID is also empty (not sure if it's an issue)

**Comment by ibo549** [comment]
Even though appointment.PatienID is made available and not null - the server side is still creating duplicate patients. This bug still exists. Maybe appointment.Patient.OwnerID should be transferred back and forth to avoid this issue. In the web app I've added OwnerID to the prototype but server side doesn't have this in patient DTO.
